[[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/rokydas"

 [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/rokydas"

 [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/rokydas136"